obj-y += eventfd/
obj-y += inotify/
obj-y += io_uring/
obj-y += mqueue/

obj-y += flock.o
obj-y += getauxval.o
obj-y += ioctl.o
obj-y += mount.o
obj-y += reboot.o
obj-y += sysinfo.o
obj-y += umount.o
obj-y += umount2.o
